export {default as Logo} from './Logo/Logo'
export {default as NavMenu} from './NavMenu/NavMenu'
export {default as ContactLinks} from './ContactLinks/ContactLinks'
export {default as ContactButton} from './ContactButton/ContactButton'
export {default as Buscador} from './Buscador/Buscador'
export {default as VentajasList} from './VentajasList/VentajasList'