export {default as Layout} from './Layout/Layout'
export {default as Navbar} from './Navbar/Navbar'
export {default as Footer} from './Footer/Footer'
export {default as Hero} from './Hero/Hero'
export {default as Ventajas} from './Ventajas/Ventajas'
export {default as Proceso} from './Proceso/Proceso'
export {default as Banner} from './Banner/Banner'
export {default as Testimonios} from './Testimonios/Testimonios'