import Head from "next/head";
import Image from "next/image";
// Styles
import styles from "styles/Home.module.css";
// Containers
import {Hero,Ventajas,Proceso,Banner,Testimonios} from 'containers'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="home">
        <Hero/>
        <Ventajas/>
        <Proceso/>
        <Banner/>
        <Testimonios/>
      </main>
    </>
  );
}
