import Head from "next/head";
import Image from "next/image";
// Styles
import styles from "styles/Home.module.css";
// Containers
import {Hero,Ventajas,Proceso,Banner,Testimonios} from 'containers'
// Constants
import { ventajas} from "../constants";

export default function Home({ventajas}) {
  return (
    <>
      <Head>
        <title>CliCasa</title>
        <meta name="description" content="Generated by CliCasa" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="home">
        <Hero/>
        <Ventajas ventajas={ventajas}/>
        <Proceso/>
        <Banner/>
        <Testimonios/>
      </main>
    </>
  );
}

export async function getStaticProps() {
  return {
      props: {
          ventajas
      }
  }
}